name: Daily DB Backup to Google Drive

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 12:00 AM UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf

      - name: Upload DB to Google Drive
        run: |
          rclone copy tasks.db mydrive:/AutoDeployXBackup --create-empty-src-dirs
