name: Daily Backup to Google Drive

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Setup Rclone Config (Decode base64)
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" | base64 --decode > ~/.config/rclone/rclone.conf

      - name: Upload tasks.db to Google Drive
        run: |
          rclone copy "pythonProject/tasks.db" "mydrive:/AutoDeployXBackup" --create-empty-src-dirs
